name: Scrape Job Postings

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy

    - name: Run Scrapy spider
      run: |
        scrapy crawl job_post_spider -o job_list_scrapy.csv
      working-directory: ./job_post

    - name: Commit files
      run: |
        git config --local user.name "${{ github.actor }}"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        
        git add job_post/*
        
        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "GH ACTION Headlines"
          git push origin main
        else
          echo "No changes to commit."
        fi
      env:
        REPO_KEY: ${{ secrets.JOB_SCRAPING_TOKEN }}
